package kg.geektech.game.game_entities;

public enum SuperAbility {
    HEAlTH, CRITICAL_DAMAGE, BOOST, SAVE_DAMAGE_REVERT, STUN, ABSORB_DAMAGE,
    BOSS_THINK_U_DIED, DISAPPEAR, CLONE_OR_HENCHMEN,YOUR_LIFE_NECESSARY_THEN_MINE,
    BECOME_BIGGER, IT_IS_MINE


}
